### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by junglert** [phkam/bat-status#2]
Could you add some more comments to your code?

Would make it a lot easier to understand

**Comment by phkam** [comment]
Please specify the parts that need clarification

**Comment by junglert** [comment]
i.e. line 106
`RESULT="${RESULT%%*( )}"`

**Comment by phkam** [comment]
Right; this was already on my list. There is actually magic happening here.
If you spot any more lines that could benefit from clarification, please add them here.

**Comment by junglert** [comment]
Thank you, i am trying to find more lines that i dont understand
